name: build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
  push:
    branches:
      - master
      - dev
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          path: src
      - name: Checkout Branch cooked
        uses: actions/checkout@v4
        with:
          ref: dist
          path: dist
      - name: gen
        id: gen
        run: |
          cd src && \
          pip install -r requirements.txt && \
          DEBUG=1 python iptv.py
          cp dist/* ../dist/
          echo "gen_time=$(date '+%Y-%m-%d %H:%M:%S %z')" >>$GITHUB_OUTPUT
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./dist
          commit_message: update ${{ steps.gen.outputs.gen_time }}
          add_options: '-A'
          push_options: '--force'
