name: generate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - master
jobs:
  cook:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: gen
        run: |
          pip install -r requirements.txt && \
          DEBUG=1 python iptv.py
          echo "gen_time=$(date '+%Y-%m-%d %H:%M:%S %z')" >>$GITHUB_OUTPUT
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update ${{ steps.fire.outputs.gen_time }}
          add_options: '-A'
          push_options: '--force'
