name: epg
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
env:
  EPG_URL: https://live.fanmingming.com/e.xml
jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dist
      - name: fetch
        id: fetch
        run: |
          curl -Ls --compressed -o epg.xml https://live.fanmingming.com/e.xml && \
            gzip -c epg.xml > epg.xml.gz && \
            echo "fetch_time=$(date '+%Y-%m-%d %H:%M:%S %z')" >>$GITHUB_OUTPUT
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update ${{ steps.fetch.outputs.fetch_time }}
          add_options: '-A'
          push_options: '--force'
